### ISSUE TITLE
Add an editorial plan in PDF with all scheduled posts for the next month.

### ISSUE THREAD

**Issue by jp-hoehmann** [valomedia/aldo#56]
Aldo should be Able to make a PDF containing a schedule for posts, that are planned for the next month.

**Comment by jp-hoehmann** [comment]
Depends #52 #54

**Comment by jonathanengelland** [comment]
It should be possible to choose between month and week ... 2 weeks etc.!

**Comment by jp-hoehmann** [comment]
Etc.?  Is a list with a few predefined options enough, or does the user need to be able to freely choose any number of days, weeks, months, years?

If the former is the case, is this list missing anything?  Which options are unnecessary?
* Weekly
* Biweekly
* Monthly
* Bimonthly
* Quarterly
* Triannually
* Biannually
* Sesquiannually
* Annually
* Sesquiennially
* Biennially
* Triennially

**Comment by jonathanengelland** [comment]
We can use all these divisions!

But we can also omit the following:
Sesquiannually
Sesquienniell
Triennally

**Comment by jp-hoehmann** [comment]
No time. Closing.
